title: "Ravan Buddha"
description: "Software Engineer | AI, ML, LLM, GenAI, Full-Stack, Cloud, Data Science"
author: "Ravan Ranveer Buddha"
email: "ravan6666@gmail.com"
linkedin: "https://www.linkedin.com/in/ravanranveer18/"
github: "https://github.com/RavanRanveer"


